version: "3"

networks:
  todo:
    external: true

services:
  todo-test:
    container_name: todo-test
    image: node:10
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3005:3005"
    command: /bin/bash -c 'yarn; yarn test;'
    networks:
      - todo
